# PLA算法测试 --数据集来源林轩田老师课程

1.导入文件和numpy

In [1]:
from loadfile import *
from PLA_algorithm import *

In [2]:
import numpy

2.打开数据集

In [3]:
X, Y = loadfile('./data/hw1_15_train.dat')

In [4]:
X

array([[0.97681 , 0.10723 , 0.64385 , 0.29556 ],
       [0.67194 , 0.2418  , 0.83075 , 0.42741 ],
       [0.20619 , 0.23321 , 0.81004 , 0.98691 ],
       ...,
       [0.93895 , 0.93941 , 0.72496 , 0.95655 ],
       [0.046136, 0.94413 , 0.038311, 0.26812 ],
       [0.072491, 0.2242  , 0.62592 , 0.67238 ]])

In [5]:
Y

array([ 1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1., -1.,  1.,  1.,  1.,
       -1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
       -1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1., -1., -1.,  1.,
       -1., -1.,  1., -1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1., -1., -1.,  1.,
       -1.,  1., -1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,
        1., -1.,  1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,
       -1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1.,
        1.,  1., -1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.,
       -1., -1.,  1., -1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1., -1., -1., -1.,  1., -1.,  1., -1.,  1.,
       -1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1.,  1.,  1

3.处理数据集X和结果集Y

In [6]:
# 添加偏压 --添加首列1.000 float
X = np.hstack((np.ones((X.shape[0],1)), X))
# 初始化权重
W = np.zeros(X.shape[1])

In [7]:
X

array([[1.      , 0.97681 , 0.10723 , 0.64385 , 0.29556 ],
       [1.      , 0.67194 , 0.2418  , 0.83075 , 0.42741 ],
       [1.      , 0.20619 , 0.23321 , 0.81004 , 0.98691 ],
       ...,
       [1.      , 0.93895 , 0.93941 , 0.72496 , 0.95655 ],
       [1.      , 0.046136, 0.94413 , 0.038311, 0.26812 ],
       [1.      , 0.072491, 0.2242  , 0.62592 , 0.67238 ]])

In [8]:
W

array([0., 0., 0., 0., 0.])

4.测试PLA

In [9]:
# 初始版本
"""1.(37, 0.9975)"""
halt, accuracy= PLA_algo1(X, Y)
halt, accuracy

(37, 0.9975)

In [10]:
# 2000次迭代版本
"""1.(34.2895, 0.98198)"""
halt, accuracy = PLA_algo2(X, Y)
halt, accuracy

(34.2895, 0.98198)

5.测试pocket PLA

In [11]:
"""1.(29, 2, 0.7625)"""
# 单次版本
halt, count, accuracy = pocket_PLA(X, Y)
halt, count, accuracy

(29, 2, 0.7625)

In [12]:
# 2000次迭代求均值
"""1.(23, 2, 0.7225)"""
halt, count, accuracy = pocket_PLA_algo1(X, Y)
halt, count, accuracy

(23, 2, 0.7225)

END